import { tmpheaders } from "@/constants/constants";
import "@/styles/globals.css";
import Header from "./components/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Header
          categories={tmpheaders.categories}
          logoSrc={tmpheaders.logoSrc}
        />
        {children}
      </body>
    </html>
  );
}
